# Generated by Django 3.1.4 on 2020-12-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'ordering': ['name']},
        ),
    ]
