# Generated by Django 3.1.4 on 2021-01-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_auto_20201222_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='gender',
            field=models.CharField(default='male', max_length=50),
        ),
    ]
