# Generated by Django 3.1.4 on 2021-01-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_authors_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='generation',
            field=models.CharField(default='', max_length=50),
        ),
    ]
